spring:
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
  messages:
    basename: i18n.loginInternet
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    url: jdbc:mysql://localhost:3306/chatroom
    data-username: root
    data-password: 111111
server:
  port: 8081
  servlet:
    context-path: /chatRoom
